config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'

  get "home/about" => "homes#about"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get 'followings' => 'relationships#follows', as: 'user_follow'
  	get 'followers' => 'relationships#followers', as: 'user_followers'
    get :followers, on: :member
  end

  get 'search' => 'searches#search', as: 'search'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "forward_match"
      @books = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @books = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @books = Book.where("#{word}")
    elsif search == "partial_match"
      @books = Book.where("title LIKE?","%#{word}%")
    else
      @books = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def self.search(search,word)
    if search == "forward_match"
      @users = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @users = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @users = User.where(name: "#{word}")
    elsif search == "partial_match"
      @users = User.where("name LIKE?","%#{word}%")
    else
      @users = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [ :top, :about ]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    if current_user
      flash[:notice] = "Welcome! You have signed up successfully."
      user_path(current_user)
    else
      flash[:notice] = "Welcome! You have signed up successfully."
      user_path(current_user)
    end
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all
    @user = User.find_by(id: current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new = Book.new
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
     @books = Book.all
     @user = current_user
     render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def correct_user
    book = Book.find(params[:id])
    user = book.user
    if current_user != user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id )
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id )
    favorite.destroy
    # redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def follows
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to request.referer
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to request.referer
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    search = params[:search_method]
    word = params[:search_word]

    if @range == '1'
      @users = User.search(search,word)
      if @users.empty?
        @users = User.all
      end
    else
      @books = Book.search(search,word)
      if @books.empty?
        @books = Book.all
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = User.find_by(id: current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comment-btn.html.erb
<%= form_with(model:[book, book_comment], path:book_book_comments_path(book), remote: true ) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %><br>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_book_comment-form.html.erb
<%= form_with(model:[book, book_comment]) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %><br>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_comments.html.erb
<table>
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user) do %>
        <%= attachment_image_tag book_comment.user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
        <br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <td>
      <% if book_comment.user == current_user %>
        <%= link_to "destroy", book_book_comment_path(book_id: book.id, id: book_comment.id), method: :delete, remote: true %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/book_comments/create.js.erb
$("#comments").html("<%= j(render partial: 'book_comments/comments', locals: {book: @book} ) %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comments").html("<%= j(render partial: 'book_comments/comments', locals: {book: @book} ) %>");

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
<%= @book.errors.count %>error
<% @book.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<%= form_with model:@book, local: true do |f| %>
  <h6>Title</h6>
  <%= f.text_field :title %>
  <h6>Opinion</h6>
  <%= f.text_area :body %>
  <br><%= f.submit 'Update Book' %>
  <br>
  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
<% end %>

<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= attachment_image_tag current_user, :profile_image, size: "100x100", fallback: "no_image.jpg" %>
        <table class='table'>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_user_follow_path(@user.id) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_user_followers_path(@user.id) %></th>
          </tr>
        </table>

        <% if current_user != @user %>
          <% if @user.followed_by?(current_user) %>
            <p><%=link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %></p>
              <% else %>
            <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
          <% end %>
        <% end %>

        <% if current_user == @user %>
          <div class='row'>
            <%=link_to "", edit_user_path(current_user.id), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20093" %>
          </div>
        <% end %>

        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label><br>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label><br>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book' %>
          </div>
        <% end %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
                    <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
                <!--週間いいね数順-->
                <td class="favorite-btn<%= book.id %>">
                  <%= render 'favorites/favorite-btn', book: book %>
                </td>
                <td>
                  <p>コメント数:<%= book.book_comments.count %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</main>

app/views/books/show.html.erb
<% if @new.errors.any? %>
  <%= @new.errors.count %>error
  <% @new.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <table class='table'>
          <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image.jpg" %>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_user_follow_path(@user.id) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_user_followers_path(@user.id) %></th>
          </tr>
        </table>

        <% if current_user != @user %>
          <% if @user.followed_by?(current_user) %>
            <p><%=link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %></p>
              <% else %>
            <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
          <% end %>
        <% end %>

        <% if current_user == @user %>
          <div class='row'>
            <%=link_to "", edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20093" %>
          </div>
        <% end %>

        <h2 class="mt-3">New book</h2>
        <%= form_with model:@new, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label><br>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label><br>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book' %>
          </div>
        <% end %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Book detail</h2>
        <table class='table table-hover table-inverse'>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @book.user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
                <br>
                <%= @user.name %>
                <% end %>
                </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <td class="favorite-btn<%= @book.id %>">
                <%= render 'favorites/favorite-btn', book: @book %>
              </td>
              <td>
                <p>コメント数:<%= @book.book_comments.count %></p>
              </td>
              <% if @user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
                <td><%= link_to "Destroy", book_path(@book.id), method: :delete ,data: { confirm: "本当に消しますか？" } %></td>
              <% end %>
            </tr>
          </tbody>
        </table>

          <div id="comments">
            <%= render 'book_comments/comments', book: @book %>
          </div>

        <div id="new-comment">
          <%= render 'book_comments/book_comment-form', book: @book, book_comment: @book_comment %>
        </div>
      </div>

    </div>
  </div>
</main>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
<p>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
</p>
<% else %>
<p>
  <%= link_to book_favorites_path(book), method: :post, remote: true  do %>
    ♡<%= book.favorites.count %>
  <% end %>
</p>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn"+<%= @book.id %>).html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn"+<%= @book.id %>).html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in",new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign Up",new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/relationships/followers.html.erb
<h1>Follower Users</h1>

<table class='table table-hover table-inverse'>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td>フォロー数:<%= user.followings.count %></td>
                <td>フォロワー数:<%= user.followers.count %></td>
                <td><%= link_to "Show",user_path(user.id) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/relationships/follows.html.erb
<h1>Follow Users</h1>

<table class='table table-hover table-inverse'>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td>フォロー数:<%= user.followings.count %></td>
                <td>フォロワー数:<%= user.followers.count %></td>
                <td><%= link_to "Show",user_path(user.id) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/searches/search.html.erb
<div>
  <% if @range == '1' %>

    <h2>Users search for "test"</h2>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td>
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                  <p><%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></p>
                  <% else %>
                  <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to "Show",user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <% else %>
      <div>
        <h2>Books search for "test"</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<h1>User info</h1>

<% if @user.errors.any? %>
<%= @user.errors.count %>error
<% @user.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<%= form_with model: @user, local:true do |f| %>
  <h4>Name</h4>
  <%= f.text_field :name %>
  <h4>Image</h4>
  <%= f.attachment_field :profile_image %>
  <h4>Introduction</h4>
  <%= f.text_area :introduction %>
  <br>
  <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error
  <% @book.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
<% end %>

<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= attachment_image_tag current_user, :profile_image, size: "100x100", fallback: "no_image.jpg" %>
        <table class='table'>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_user_follow_path(@user.id) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_user_followers_path(@user.id) %></th>
          </tr>
        </table>

        <% if current_user != @user %>
          <% if @user.followed_by?(current_user) %>
            <p><%=link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %></p>
              <% else %>
            <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
          <% end %>
        <% end %>

        <% if current_user == @user %>
          <div class='row'>
            <%=link_to "", edit_user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20093" %>
          </div>
        <% end %>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label><br>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label><br>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book' %>
          </div>
        <% end %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td>フォロー数:<%= user.followings.count %></td>
                <td>フォロワー数:<%= user.followers.count %></td>
                <td>
                  <% if current_user != user %>
                    <% if user.followed_by?(current_user) %>
                      <p><%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></p>
                      <% else %>
                      <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
                    <% end %>
                  <% end %>
                </td>
                <td><%= link_to "Show",user_path(user.id) %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image.jpg" %>
        <table class='table'>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_user_follow_path(@user.id) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_user_followers_path(@user.id) %></th>
          </tr>
        </table>

        <% if current_user != @user %>
          <% if @user.followed_by?(current_user) %>
            <p><%=link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %></p>
              <% else %>
            <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
          <% end %>
        <% end %>

        <% if current_user == @user %>
          <div class='row'>
            <%=link_to "", edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20093" %>
          </div>
        <% end %>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book, local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label><br>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label><br>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book' %>
          </div>
        <% end %>
      </div>

      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.books.each do |book| %>
            <tr></tr>
            <tr>
              <td><%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
                  <% end %>
                  </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
</main>